---
- hosts: alertmanager
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - alertmanager

- hosts: node-exporter
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - node-exporter

- hosts: prometheus
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - prometheus

- hosts: grafana
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - grafana